### PR TITLE
Fanart/poster change

### PR DESCRIPTION
**Pull request by Makhuta**
- logging all used/possible images for fanart/poster

### CODE REVIEW

**Comment by mkanet** [comment]
Thank you!  I'll test it as soon as I'm home.

**Comment by mkanet** [comment]
I'm having a very hard time identifying the correct path to use for posters in the version you just provided.  There are so many listed in the log (which I have to check one by one to see what each one looks like).  I unfortunately, don't have that much time to go through them all.  I think it would be easier to look at the original `sensor.py` code (before config_flow version of this integration) to see how it determined the correct TV show poster paths in its attributes and compare it to how it's done in the current config_flow version of this Integration.  I can do this in the next week or so when I have more time.

**Comment by Makhuta** [comment]
Ok, I will look into it when I got the time.

**Comment by mkanet** [comment]
I was able to match the old behavior (after looking at the old version of this integration before the config_flow rewrite)

I replaced the 2 lines below in `parser.py`

```python
thumb = item.get("thumb", item.get("parentThumb", item.get("grandparentThumb", None)))
art = item.get("art", item.get("grandparentArt", None))
```

with...

```
if item['type'] == 'movie':
    thumb = item.get("thumb", "")
    art = item.get("art", "")
elif item['type'] == 'episode':
    thumb = item.get("grandparentThumb", "")
    art = item.get("grandparentArt", "")
else:
    thumb = item.get("thumb", item.get("parentThumb", item.get("grandparentThumb", None)))
    art = item.get("art", item.get("grandparentArt", None))
```

It is now displaying correct poster images.  At least, it _should_ display the same posters and fanart as before.  Ill test it more before pushing the fix...

**Comment by mkanet** [comment]
https://github.com/custom-components/sensor.plex_recently_added/commit/821091f197484af734064037ccab64fdbaad24eb

**Comment by mkanet** [comment]
@Makhuta sorry to bug you again.  I know you are busy just like I am. 

Unrelated to the above issue (which I already fixed), a user is reporting that the new "Verify SSL" config_flow feature doesn't seem to do anything:
https://github.com/custom-components/sensor.plex_recently_added/issues/78#issuecomment-2135886474

I looked at the config_flow code related to "Verify SSL", it "seems" to be correct.  However, I wasn't able to actually verify that it does what its supposed to.  **When I generate an invalid SSL certificate (for my NGINX server to use for Plex) the invalid certificate causes my entire NGINX server to hang.**

**When you have time, could you please confirm that this feature actually works as intended in the real world?**  Maybe you have better luck testing it than me.  In a worst case, if you can't do this (or don't have any time), maybe we should just remove this feature completely since it wasn't even in the previous version without config_flow.

**Comment by Makhuta** [comment]
If I remember correctly the verify ssl is for the request header because when I tried the sceneario with ssl enabled and verify ssl enabled but the certificate was not valid/was unknown the HA logged warning so it was intended for this purpose, it could be removed the integration will work just fine without it but there is posibility of warnings

**Comment by mkanet** [comment]
Can you please let me know for sure when you have time?

**Comment by mkanet** [comment]
I went ahead and removed the setting completely from config_flow in release 0.4.6.  It seems to be working just fine without any errors when using HTTP or HTTPS.

**Comment by mkanet** [comment]
Hi @Makhuta I need your help.  I hope you are still available.  This integration is finally approved to be added to HACS.  However, the moderators will not allow the integration to be added with the changes you made to redirect.py.  They said:   

**Ludeeus — Yesterday at 10:03 PM**
https://github.com/custom-components/sensor.plex_recently_added/blob/master/custom_components/plex_recently_added/redirect.py
This part will allow anyone who can reach any home assistant installation with this integration to force it to proxy authenticated requests against plex.

Do think you can make the smallest changes necessary to make this integration safer?

**Comment by mkanet** [comment]
@Makhuta Do you think you could make the changes necessary when you get time?  Unfortunately, the moderators wont wait a very long time for us to fix this.  I'm not sure the best way to handle this.

**Comment by mkanet** [comment]
@Makhuta This might help:
https://developers.home-assistant.io/docs/auth_api/

**Comment by Makhuta** [comment]
I looked into it and absolutely missed the threat they mentioned. I hope this fix should suffice since it forces the IDs (the parameters of the request) to be numbers instead of direct path which was not secure. It still should work as before

**Pull request closed without merging**
