### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by Makhuta**
- ssl issue with HomeAssistant redirect (from secured HA to unsecured Plex)

### CODE REVIEW

**Comment by mkanet** [comment]
Thank you @Makhuta.  I just tested it.. It works correctly now.  Thanks for fixing it so quickly!

**Comment by Makhuta** [comment]
I am so happy to hear that it works, even on your side 😏

**Comment by mkanet** [comment]
Hi @Makhuta , it looks like there is another issue caused by the complete rewrite of this integration. 

When using the setting:  `image_style: poster` on the default "show" sensor, it is displaying fanart images instead of poster images (see below screenshot).  This only happens to me for the "show" sensor, not "movie" sensor.  The movie sensor displays fanart and poster images correctly.

Can you please try to see if you can reproduce this?

image

**Comment by Makhuta** [comment]
I will look into it, it is most likely caused by the style I made the poster grabber from the xml I am gonna first make log that will show you all possible variants and you can decide what you want there. 
(it will only show you the URL like in the sensor attribute so you will need to put it in your URL bar like so: HOMEASSISTANT_URL/LOG_URL but I think you've got the idea and it is just temporary for you to decide)
(the log will probably be i dictionary format like this: 
```json
{
    type: 'TYPE_NAME',
    url: 'URL_FOR_YOU_TO_COPY'
}
```

PS. But bare in mind to check the other types (artist, photo, ect.) that it is compatible even with them if not I will have to make some checks for them so that the poster (fan art) is still grabbed.

**Comment by mkanet** [comment]
@Makhuta thank you very much.  Whatever URLs that were used in the versions of this integration (before being completely rewritten) were very reliable and consistent.  Hopefully, I can identify the same URLs that were used before in previous versions.

I don't have any experience with other types on Plex such as artists, photo, music, etc.  Whatever it is, I'm confident we will find the best URLs to use.

Let me know when you have something for me to try...

**Pull request merged**
